# Generated by Django 5.2.12 on 2026-03-09 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Items",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Category", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="expenditure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Spent", models.IntegerField(null=True)),
                (
                    "Item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Expenditure.items",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Date",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date", models.DateField()),
                (
                    "Item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Expenditure.items",
                    ),
                ),
            ],
        ),
    ]
