# Generated by Django 5.2.4 on 2026-06-04 21:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Expenditure", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expenditure",
            name="date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
